### ISSUE TITLE
Read only defined role with s3:PutObject

### ISSUE THREAD

**Issue by slyness** [spotinst/spotinst-examples#29]
https://github.com/spotinst/spotinst-examples/blob/6e00fda4079dedbec9877672e06bfc825d0b9d3a/Policies/AWS/Spot-AWS-Eco-Restricted-ReadOnly.json#L30

Just curious why this role is described as ReadOnly but had s3:PutObject, s3:PutObjectTagging and s3:PutObjectAcl in the S3SyncPermissions policy.

https://github.com/spotinst/spotinst-examples/blob/master/Policies/AWS/Spot-AWS-Eco-Restricted-ReadOnly.json#L33-L34

**Comment by stevenfeltner** [comment]
@slyness This is permission to access Spot's Bucket in our AWS account. Its read-only for all resources in your AWS account.
